### ISSUE TITLE
Unprovision application TypeError

### ISSUE THREAD

**Issue by samedder** [Microsoft/service-fabric-cli#6] opened 2017-07-26 04:10 UTC
When running the unprovision command:

```bash
sfctl application unprovision --application-type-name CalcServiceApp --application-type-version 1.0
```

A `TypeError` is raised attempting to deserialise the `FabricError` type object from the response. The following stack trace is shown:

```
__init__() takes exactly 2 arguments (1 given)
Traceback (most recent call last):
  File "/Users/samed/source/azure/sf-cli/env27/lib/python2.7/site-packages/knack/cli.py", line 125, in invoke
    cmd_result = self.invocation.execute(args)
  File "/Users/samed/source/azure/sf-cli/env27/lib/python2.7/site-packages/knack/invocation.py", line 85, in execute
    cmd_result = parsed_args.func(params)
  File "/Users/samed/source/azure/sf-cli/env27/lib/python2.7/site-packages/knack/commands.py", line 67, in __call__
    return self.handler(*args, **kwargs)
  File "/Users/samed/source/azure/sf-cli/env27/lib/python2.7/site-packages/knack/commands.py", line 123, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "/Users/samed/source/azure/sf-cli/env27/lib/python2.7/site-packages/azure/servicefabric/service_fabric_client_ap_is.py", line 2199, in unprovision_application_type
    raise models.FabricErrorException(self._deserialize, response)
  File "/Users/samed/source/azure/sf-cli/env27/lib/python2.7/site-packages/azure/servicefabric/models/fabric_error.py", line 48, in __init__
    super(FabricErrorException, self).__init__(deserialize, response, 'FabricError', *args)
  File "/Users/samed/source/azure/sf-cli/env27/lib/python2.7/site-packages/msrest/exceptions.py", line 138, in __init__
    self.error = deserialize.dependencies[resp_type]()
TypeError: __init__() takes exactly 2 arguments (1 given)
```

While the unprovision causes an error, subsequent attempts to list the provision application type do not show the application when calling `application type-list`

**Comment by linggengmsft** [comment] 2017-09-09 18:01
The returning code is set wrong. Will fix it in latest release.

**Comment by linggengmsft** [comment] 2017-09-15 21:31
FYI. This issue has been merged to main branch.

**Comment by samedder** [comment] 2017-09-18 22:23
Pending testing and verification

**Comment by snapnurse-joshuamatthews** [comment] 2017-09-19 18:21
When I execute unprovision, it seems that sfctl isn't sending the correct parameters to the api

```
msrest.http_logger : Request URL: 'http://192.168.50.50:19080/ApplicationTypes/MicroservicesType/$/Unprovision?api-version=3.0&timeout=60'
msrest.http_logger : Request method: 'POST'
msrest.http_logger : Request headers:
msrest.http_logger :     'User-Agent': 'python/3.6.2 (Darwin-16.7.0-x86_64-i386-64bit) requests/2.18.4 msrest/0.4.14 servicefabricclientapis/6.0.0rc1'
msrest.http_logger :     'Accept-Encoding': 'gzip, deflate'
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'Connection': 'keep-alive'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'Content-Length': '35'
msrest.http_logger : Request body:
msrest.http_logger : {"ApplicationTypeVersion": "1.0.0"}
msrest.http_logger : Response status: 200
msrest.http_logger : Response headers:
msrest.http_logger :     'Content-Length': '0'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger : Response content:
msrest.http_logger : b''
```

**Comment by linggengmsft** [comment] 2017-09-19 21:11
@snapnurse-joshuamatthews , "MicroservicesType" is your application type name so the request is correct. Are you seeing any errors? The response status is supposed to be 202. What is your cluster version?

**Comment by snapnurse-joshuamatthews** [comment] 2017-09-19 21:19
look at the request body, applicationTypeName is not there. I am getting an error because the required parameter is missing. Am I passing it in wrong?

**Comment by linggengmsft** [comment] 2017-09-19 21:21
It is by-design in the path instead of body. Please refer to our doc: 
https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-api-unprovisionapplicationtype

**Comment by snapnurse-joshuamatthews** [comment] 2017-09-19 21:21
@linggengmsft the response status is 200, but there is a response message saying that a required parameter is missing, and in the documentation ApplicationTypeName is a required parameter.

**Comment by snapnurse-joshuamatthews** [comment] 2017-09-19 21:22
Okay I see, not sure why the error then. I am using it through python on a mac, maybe related

**Comment by linggengmsft** [comment] 2017-09-19 21:23
@snapnurse-joshuamatthews , what error were you seeing? The request you pasted should work. And what is the version of your cluster btw?

**Comment by snapnurse-joshuamatthews** [comment] 2017-09-19 21:30
If I use a rest client, the route

`http://192.168.50.50:19080/ApplicationTypes/MicroservicesType/$/Unprovision?api-version=3.0&timeout=60`

with the body 

```
 {
  "ApplicationTypeVersion": "1.0.0",
}
```

returns a 400 error

` {"Error":{"Code":"E_INVALIDARG","Message":"Invalid argument"}}`

but if I change the body to 

```
 {
  "ApplicationTypeVersion": "1.0.0",
  "ApplicationTypeName": "MicroserviceType"
}
```

then it works. This might be related to my cluster being on linux, maybe there are some differences in the api.

**Comment by linggengmsft** [comment] 2017-09-19 21:33
@snapnurse-joshuamatthews 
Please provide your cluster version for us to investigate.

**Comment by snapnurse-joshuamatthews** [comment] 2017-09-19 21:36
Where do I find it?

**Comment by snapnurse-joshuamatthews** [comment] 2017-09-19 21:40
I used the vagrant-linux vm from the Microsoft docs.

**Comment by linggengmsft** [comment] 2017-09-19 22:03
@snapnurse-joshuamatthews 
You could query node info: https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-api-getnodeinfo
And if there isn't a cluster upgrade going on, the node version would be the cluster version.

**Comment by snapnurse-joshuamatthews** [comment] 2017-09-19 22:09
Node version is 5.7.12.1

**Comment by oanapl** [comment] 2017-09-19 23:56
Can you try removing the ',' from the body:
 {
  "ApplicationTypeVersion": "1.0.0"
}

instead of 
 {
  "ApplicationTypeVersion": "1.0.0",
}

**Comment by snapnurse-joshuamatthews** [comment] 2017-09-20 00:25
Ah that does seem to fix the rest client. I guess thats not the source of the errors I'm seeing in console. Pasted the original error below which I though was caused by missing param but now no idea. 

`Joshuas-MacBook-Pro:SnapNurse joshuamatthews$ sfctl application unprovision --application-type-name SnapNurseMicroservicesType --application-type-version 1.0.0 --debug
Command arguments: ['application', 'unprovision', '--application-type-name', 'SnapNurseMicroservicesType', '--application-type-version', '1.0.0', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x10feaab70>, <function OutputProducer.on_global_arguments at 0x10ff5f620>, <function CLIQuery.on_global_arguments at 0x10ff82158>]
Event: CommandInvoker.OnPreCommandTableCreate [<function CLILogging.remove_logger_flags at 0x10feaabf8>]
Event: CommandLoader.OnLoadArguments []
Event: CommandInvoker.OnPostCommandTableCreate []
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs []
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x10ff5f6a8>, <function CLIQuery.handle_query_parameter at 0x10ff821e0>]
msrest.pipeline : Configuring request: timeout=100, verify=True, cert=None
msrest.pipeline : Configuring redirects: allow=True, max=30
msrest.pipeline : Configuring proxies: ''
msrest.pipeline : Evaluate proxies against ENV settings: True
msrest.pipeline : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
urllib3.connectionpool : Starting new HTTP connection (1): 192.168.50.50
urllib3.connectionpool : http://192.168.50.50:19080 "POST /ApplicationTypes/SnapNurseMicroservicesType/$/Unprovision?api-version=3.0&timeout=60 HTTP/1.1" 200 0
msrest.http_logger : Request URL: 'http://192.168.50.50:19080/ApplicationTypes/SnapNurseMicroservicesType/$/Unprovision?api-version=3.0&timeout=60'
msrest.http_logger : Request method: 'POST'
msrest.http_logger : Request headers:
msrest.http_logger :     'User-Agent': 'python/3.6.2 (Darwin-16.7.0-x86_64-i386-64bit) requests/2.18.4 msrest/0.4.14 servicefabricclientapis/6.0.0rc1'
msrest.http_logger :     'Accept-Encoding': 'gzip, deflate'
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'Connection': 'keep-alive'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'Content-Length': '35'
msrest.http_logger : Request body:
msrest.http_logger : {"ApplicationTypeVersion": "1.0.0"}
msrest.http_logger : Response status: 200
msrest.http_logger : Response headers:
msrest.http_logger :     'Content-Length': '0'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger : Response content:
msrest.http_logger : b''
__init__() missing 1 required positional argument: 'error'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/knack/cli.py", line 125, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.6/site-packages/knack/invocation.py", line 85, in execute
    cmd_result = parsed_args.func(params)
  File "/usr/local/lib/python3.6/site-packages/knack/commands.py", line 67, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/knack/commands.py", line 123, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "/usr/local/lib/python3.6/site-packages/azure/servicefabric/service_fabric_client_ap_is.py", line 2682, in unprovision_application_type
    raise models.FabricErrorException(self._deserialize, response)
  File "/usr/local/lib/python3.6/site-packages/azure/servicefabric/models/fabric_error.py", line 48, in __init__
    super(FabricErrorException, self).__init__(deserialize, response, 'FabricError', *args)
  File "/usr/local/lib/python3.6/site-packages/msrest/exceptions.py", line 138, in __init__
    self.error = deserialize.dependencies[resp_type]()
TypeError: __init__() missing 1 required positional argument: 'error'`

**Comment by samedder** [comment] 2017-09-21 03:26
That's the same issue as reported at the beginning of this thread.

**Closed** 2018-06-08 23:57 UTC
Labels: bug
